/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Andy Cuccaro (https://sketchfab.com/andycuccaro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tux-157de95fa4014050a969a8361a83d366
Title: Tux
*/

// The new Tux model uses DRACO Compression (better Load Times)

import { useGLTF } from "@react-three/drei";
import useResponsiveScale from "@/utils/useResponsiveScale";

export default function TuxModel(props) {
  const { nodes, materials } = useGLTF("/models/tux.glb");
  const scale = useResponsiveScale();
  return (
    <group {...props} dispose={null}>
      <group
        // position={[0.002, -0.027, -0.719]}
        // rotation={[-Math.PI / 2, 0, 0]}
        scale={scale}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Tux-printable_0"].geometry}
          material={materials.black}
          position={[0.002, -0.027, -0.719]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Tux-printable_1"].geometry}
          material={materials.white}
          position={[0.002, -0.027, -0.719]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Tux-printable_2"].geometry}
          material={materials.orange}
          position={[0.002, -0.027, -0.719]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/tux.glb");
